---
version: '3.7'

services:
  fanuc_driver:
    container_name: fanuc_driver
    image: ladder99/fanuc-driver:latest
    restart: always
    depends_on:
      - mosquitto
    networks:
      - fanuc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/fanuc-volumes/fanuc-driver:/etc/fanuc:rw
    logging:
      options:
        max-file: "5"
        max-size: "1m"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    networks:
      - fanuc
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/fanuc-volumes/mosquitto/config:/mosquitto/config:rw
      - ~/fanuc-volumes/mosquitto/data:/mosquitto/data:rw
      - ~/fanuc-volumes/mosquitto/log:/mosquitto/log:rw
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"

  streamsheets:
    image: cedalo/streamsheets:2-milestone-rpi
    container_name: streamsheets
    restart: always
    depends_on:
      - streamsheets-internal-mongodb
    networks:
      - fanuc
    ports:
      - "11883:1883"
      - "8081:8081"
    links:
      - streamsheets-internal-mongodb
    environment:
      MONGO_DATABASE: streamsheets
      MONGO_HOST: streamsheets-internal-mongodb
      MONGO_PORT: 27017
      MONGO_USER_DB_URI: mongodb://streamsheets-internal-mongodb:27017/userDB
    logging:
      options:
        max-file: "5"
        max-size: "1m"

  streamsheets-internal-mongodb:
    image: andresvidal/rpi3-mongodb3
    container_name: streamsheets-internal-mongodb
    restart: always
    volumes:
      - ~/fanuc-volumes/mongo/data/db:/data/db:rw
    networks:
      - fanuc
    logging:
      options:
        max-file: "5"
        max-size: "1m"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    networks:
      - fanuc
    ports:
      - '9000:9000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    logging:
      driver: 'none'

volumes:
  portainer_data:

networks:
  fanuc:
    name: fanuc
...
